version: '3'

services:
  node:
    build:
      context: nodejs
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node src/index.js
    networks:
      - nodenetwork
    volumes:
      - node-data:/usr/src/app
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - nodenetwork
    ports:
      - "8080:80"
    depends_on:
      - node

  db:
    image: mysql:latest
    command:
      - --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=passroot
    networks:
      - nodenetwork

networks:
  nodenetwork:
    driver: bridge

volumes:
  node-data:
